Add high level and sub companies api endpoints for fetching emails
OnePageCRM/swagger pull request #20
Opened 2021-07-01 05:54 UTC by SajedHassan

2021-07-02 10:48 UTC, dem requested changes
@SajedHassan Small tiny commentt of fix

2021-07-02 10:48 UTC, dem commented on swagger.yaml
> +  email_messages/mark_all_as_read:
@SajedHassan Add / at the start:
```
/email_messages/mark_all_as_read
```

2021-07-06 00:02 UTC, vladimir-konnov approved these changes
@SajedHassan looks ok

2021-07-08 09:11 UTC, dem approved these changes
ok to go

2021-07-08 09:11 UTC, merged